# config/local.yaml

env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost"
  port: "8080"
  timeout: 4s
  idle_timeout: 30s
database:
  host: db
  db_name: postgres
  username: postgres
  password: postgres
  ssl_mode: disable